### ISSUE TITLE
May I have your initial datasets at your code?

### ISSUE THREAD

**Issue by 37814084** [mcrowson/predict-kiva#1]
Hello, Honorable author!
       I am a University student from China. I am  very interested in your task done in "predict-kiva" . A very good job and I really appreciate it!
       A question is , the datasets now in kiva API are very different from yours . Kiva hide some key field data to the public such as paid_amount, paid-date, payments etc. So I can't learn your steps in your task.
      May I have a request to get your dataset which may be retrieved three years ago?  
     Many many thanks.

**Comment by mcrowson** [comment]
Im afraid I have changed computers and can’t find the original data set. I remember it being around 10GB so I couldn’t package it with my code here. 

It was a data snapshot from http://build.kiva.org/docs/data/snapshots

Can you get a recent snapshot and just filter out entries from the past three years?

**Comment by 37814084** [comment]
Thanks for your reply! I have download the recent data snapshot, but it misses some important fields such as paid_amount, paid-date, payments etc. So I can't judge which borrower is default or delinquent. 
Also thank you very much!

**Comment by mcrowson** [comment]
Maybe those are too recent and have no repayments yet. Can you look at old loans and see if the fields are there?

**Comment by 37814084** [comment]
Thank you for your quick reply!  
According to the explanation from Kiva forum administrator , kiva wants to protect the privacy of  borrowers, so will not provide any information about borrower's payment to infer their status, which is only accessible to the lenders of the loan. So the newest data snapshot (which is released in 2016) removes all the key fields on payment.  Therefore, if I want to continue my work on default prediction, I must obtain kiva's data of 2015 or earlier.
Thank you very much for your attention and reply,  By the way(may be not very polite), if you find your original data set at some time,  may I have them(or part of them)?     

Many thanks!  Wish you happy everyday!

**Comment by mcrowson** [comment]
Well that stinks. Without the response variables it would be incredibly hard to predict. I will look in a few more places when I get home, but I doubt I still have that computer. Sorry :(

Best of luck!

**Comment by 37814084** [comment]
It doesn't matter. After all, so much time has  passed!

Also thank you.
Best of luck!

**Comment by mcrowson** [comment]
I’m sad to say I could not find the snapshot I used :(. 

Best of luck in your research.

**Comment by 37814084** [comment]
OK, thank you very much! Maybe I will give up it.
